version: '3.8'

services:
  # 1. Base de datos de series temporales (TimescaleDB)
  db:
    image: timescale/timescaledb:latest-pg16
    container_name: integrador_db
    restart: always
    environment:
      POSTGRES_DB: monitoreo_db
      POSTGRES_USER: admin_rust
      POSTGRES_PASSWORD: password_seguro_123
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - red_monitoreo
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin_rust -d monitoreo_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  # 2. Backend API en Rust (Sonda y Servidor)
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: integrador_backend
    restart: always
    # Forzamos plataforma linux/amd64 (x86_64) para emulación en tu Mac M4
    platform: linux/amd64
    ports:
      - "8080:8080"
      - "2055:2055/udp"  # Puerto para recibir flujos de NetFlow si se requiere
    environment:
      - DATABASE_URL=postgres://admin_rust:password_seguro_123@db:5432/monitoreo_db
      - RUST_LOG=info
      - PORT=8080
      - GMAIL_USER=tu_correo_de_pruebas@gmail.com
      - GMAIL_PASS=tu_contrasena_de_aplicacion
    depends_on:
      db:
        condition: service_healthy
    networks:
      - red_monitoreo

  # 3. Servidor Web Ligero para el Frontend de tu Equipo (Nginx)
  frontend:
    image: nginx:alpine
    container_name: integrador_frontend
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
    networks:
      - red_monitoreo

volumes:
  db_data:

networks:
  red_monitoreo:
    driver: bridge
