services:
  # 1. Base de datos de series temporales (TimescaleDB)
  db:
    image: timescale/timescaledb:latest-pg16
    container_name: juno_db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - juno_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  # 2. Backend API en Rust (Sonda y Servidor)
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: juno_backend
    restart: always
    platform: linux/amd64
    ports:
      - "8080:8080"
      - "2055:2055/udp"
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      - RUST_LOG=info
      - PORT=8080
      - GMAIL_USER=${GMAIL_USER}
      - GMAIL_PASS=${GMAIL_PASS}
      - JWT_SECRET=${JWT_SECRET}
      - FRONTEND_ORIGIN=${FRONTEND_ORIGIN}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - juno_network

  # 3. Servidor Web Ligero para el Frontend de tu Equipo (Nginx)
  frontend:
    image: nginx:alpine
    container_name: juno_frontend
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
    networks:
      - juno_network

volumes:
  db_data:

networks:
  juno_network:
    driver: bridge
